name: CI Pull Request

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Setup MSVC Dev Cmd
        uses: ilammy/msvc-dev-cmd@v1

      - name: Print PATH
        shell: cmd
        run: echo %PATH%

      - name: Build with Maven
        run: mvn clean install